from ubuntu:21.04

ARG DEBIAN_FRONTEND=noninteractive

# Following packages are required by conan packages (mostly xorg)
#RUN apt-get update && apt-get install -y --no-install-recommends \
#    libegl-dev xorg-dev libx11-xcb-dev libxcb-render0-dev libxcb-render-util0-dev \
#    libxcb-xkb-dev libxcb-icccm4-dev libxcb-image0-dev libxcb-keysyms1-dev \
#    libxcb-randr0-dev libxcb-shape0-dev libxcb-sync-dev libxcb-xfixes0-dev \
#    libxcb-xinerama0-dev xkb-data libxcb-dri3-dev libxcb-util-dev \
#    libglu1-mesa-dev && \
#    rm -rf /var/lib/apt/lists/*

# By default docs are not included in this docker base image
# For imgui the docs actually contain example code to which we want to
# link. 
# Modify pkg exludes
RUN sed -i s:path-exclude=/usr/share/doc:#:g /etc/dpkg/dpkg.cfg.d/excludes

# Maybe libstb-dev too
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential cmake libimgui-dev libglew-dev libsdl2-dev && \
    rm -rf /var/lib/apt/lists/*

COPY . .
RUN cmake -S . -B build -DCMAKE_BUILD_TYPE=Release && \
    cmake --build build --parallel 12
 